package com.algoExpert.demo.Admin.AdminEnums;
public enum FeatureType  {
    CREATE_PROJECT,CREATE_TABLE,CREATE_TASK,
    DELETE_TASK,
    SEARCH,SORT ,INVITE_MEMBER,ASSIGN_TASK,COMMENT
    ,SEND_EMAIL,FILE_ATTACHMENT,
    DUPLICATE,
    DELETE_PROJECT,
    DELETE_TABLE
}
