package com.algoExpert.demo.AppNotification;

import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.IOException;

@Component
public class EmailHtmlLayout {

    public String assignTaskHtml(String username,String taskTitle,String projectName,String link) {
        return ""
                + "<!DOCTYPE html>"
                + "<html lang=\"en\">"
                + "<head>"
                + "<meta charset=\"UTF-8\">"
                + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
                + "<title>Task Assignment Notification</title>"
                + "<style>"
                + "body, html {"
                + "    margin: 0;"
                + "    padding: 0;"
                + "}"
                + ".container {"
                + "    width: 100%;"
                + "    max-width: 600px;"
                + "    margin: 0 auto;"
                + "    padding: 20px;"
                + "    font-family: Arial, sans-serif;"
                + "    border: 2px solid #cdcdcd;"
                + "}"
                + ".header {"
                + "    margin-bottom: 20px;"
                + "    text-align: center;"
                + "}"
                + ".header h2 {"
                + "    padding: 10px;"
                + "    border-radius: 5px;"
                + "    color: #fff;"
                + "    background-color: #339AF0;"
                + "}"
                + ".logo {"
                + "    display: flex;"
                + "    align-items: center;"
                + "    justify-content: center;"
                + "    justify-self: flex-start;"
                + "    align-self: flex-start;"
                + "    max-width: 50px;"
                + "    height: auto;"
                + "    margin-right: 20px;"
                + "}"
                + ".content {"
                + "    padding: 20px;"
                + "    background-color: #cdcdcd;"
                + "    border-radius: 5px;"
                + "    color: #333;"
                + "}"
                + ".button {"
                + "    display: inline-block;"
                + "    background-color: #007bff;"
                + "    color: #fff;"
                + "    text-decoration: none;"
                + "    padding: 10px 20px;"
                + "    border-radius: 5px;"
                + "    margin-top: 20px;"
                + "}"
                + ".footer {"
                + "    margin-top: 20px;"
                + "    text-align: center;"
                + "    color: #666;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<table class=\"container\">"
                + "    <tr>"
                + "        <td class=\"header\" colspan=\"2\">"
                + "            <img src=\"/static/images/logo.png\" alt=\"Project Logo\" class=\"logo\">"
                + "            <h2>Task Assignment Notification</h2>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"content\" colspan=\"2\">"
                + "            <p>"+"Dear" +username+"</p>"
                + "            <p>You have been assigned the following task:</p>"
                + "            <table>"
                + "                <tr>"
                + "                    <td><strong>Task Title:</strong></td>"
                + "                    <td>"+taskTitle+"</td>"
                + "                </tr>"
                + "                <tr>"
                + "                    <td><strong>Project Title:</strong></td>"
                + "                    <td>"+projectName+"</td>"
                + "                </tr>"
                + "            </table>"
                + "            <p>Please review the task details and proceed accordingly.</p>"
                + "            <a href=\""+link+"\" class=\"button\">Go to Task</a>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"footer\" colspan=\"2\">"
                + "            <p>This is an automated notification. Please do not reply.</p>"
                + "        </td>"
                + "    </tr>"
                + "</table>"
                + "</body>"
                + "</html>";
    }
    public String confirmAccountHtml(String userName, String confirmationLink) {
        return ""
                + "<!DOCTYPE html>"
                + "<html lang=\"en\">"
                + "<head>"
                + "<meta charset=\"UTF-8\">"
                + "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
                + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
                + "<title>Email Confirmation</title>"
                + "<style>"
                + "body {"
                + "    font-family: Arial, sans-serif;"
                + "    margin: 0;"
                + "    padding: 0;"
                + "}"
                + ".container {"
                + "    width: 100%;"
                + "    max-width: 600px;"
                + "    margin: 0 auto;"
                + "    padding: 20px;"
                + "    border-collapse: collapse;"
                + "    border: 1px solid #ccc;"
                + "}"
                + ".header {"
                + "    text-align: center;"
                + "}"
                + ".logo {"
                + "    display: flex;"
                + "    align-items: center;"
                + "    justify-content: center;"
                + "    justify-self: flex-start;"
                + "    align-self: flex-start;"
                + "    max-width: 50px;"
                + "    height: auto;"
                + "    margin-bottom: 20px;"
                + "}"
                + ".header h2 {"
                + "    padding: 10px;"
                + "    border-radius: 5px;"
                + "    color: #fff;"
                + "    background-color: #339AF0;"
                + "}"
                + ".content {"
                + "    text-align: start;"
                + "    padding: 20px;"
                + "    background-color: #cdcdcd;"
                + "    border-radius: 5px;"
                + "    color: #333;"
                + "}"
                + ".button {"
                + "    display: inline-block;"
                + "    background-color: #007bff;"
                + "    color: #fff;"
                + "    text-decoration: none;"
                + "    padding: 12px 20px;"
                + "    font-size: 16px;"
                + "    border-radius: 5px;"
                + "}"
                + ".footer {"
                + "    margin-top: 20px;"
                + "    text-align: center;"
                + "    color: #666;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<table class=\"container\">"
                + "    <tr>"
                + "        <td class=\"header\">"
                + "            <img src=\"/static/images/logo.png\" alt=\"Project Logo\" class=\"logo\">"
                + "            <h2>Welcome to PMS!</h2>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"content\">"
                + "            <p>Dear " + userName + ",</p>"
                + "            <p>Thank you for creating an account on PMS. We're excited to have you on board!</p>"
                + "            <p>To get started, please confirm your email address by clicking the button below:</p>"
                + "            <a href=\"" + confirmationLink + "\" class=\"button\">Confirm Email</a>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"footer\" colspan=\"2\">"
                + "            <p>This is an automated message. Please do not reply.</p>"
                + "        </td>"
                + "    </tr>"
                + "</table>"
                + "</body>"
                + "</html>";
    }
    public String createProjectHtml(String username, String projectName) {
        return ""
                + "<!DOCTYPE html>"
                + "<html lang=\"en\">"
                + "<head>"
                + "<meta charset=\"UTF-8\">"
                + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
                + "<title>New Project Created</title>"
                + "<style>"
                + "body, html {"
                + "    margin: 0;"
                + "    padding: 0;"
                + "}"
                + ".container {"
                + "    width: 100%;"
                + "    max-width: 600px;"
                + "    margin: 0 auto;"
                + "    padding: 20px;"
                + "    font-family: Arial, sans-serif;"
                + "}"
                + ".header {"
                + "    margin-bottom: 20px;"
                + "    text-align: center;"
                + "}"
                + ".header h2 {"
                + "    padding: 10px;"
                + "    border-radius: 5px;"
                + "    color: #fff;"
                + "    background-color: #339AF0;"
                + "}"
                + ".logo {"
                + "    display: flex;"
                + "    align-items: center;"
                + "    justify-content: center;"
                + "    justify-self: flex-start;"
                + "    align-self: flex-start;"
                + "    max-width: 50px;"
                + "    height: auto;"
                + "    margin-right: 20px;"
                + "}"
                + ".content {"
                + "    padding: 20px;"
                + "    background-color: #339AF0;"
                + "    border-radius: 5px;"
                + "    color: #fff;"
                + "}"
                + ".project-image {"
                + "    max-width: 50%;"
                + "    height: auto;"
                + "    margin-top: 20px;"
                + "}"
                + ".footer {"
                + "    margin-top: 20px;"
                + "    text-align: center;"
                + "    color: #666;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<table class=\"container\">"
                + "    <tr>"
                + "        <td class=\"header\" colspan=\"2\">"
                + "            <img src=\"/static/images/logo.png\" alt=\"Project Logo\" class=\"logo\">"
                + "            <h2>New Project Created</h2>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"content\" colspan=\"2\">"
                + "            <p>Dear " + username + ",</p>"
                + "            <p>Congratulations! Your new project has been successfully created. Here's a brief overview:</p>"
                + "            <h4>Project Name: " + projectName + "</h4>"
                + "            <img src=\"/static/images/login-image2.png\" alt=\"Project Image\" class=\"project-image\">"
                + "            <p>If you have any questions or need further assistance, feel free to contact us.</p>"
                + "            <p>Best regards,<br>Project Team</p>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"footer\" colspan=\"2\">"
                + "            <p>This is an automated message. Please do not reply.</p>"
                + "        </td>"
                + "    </tr>"
                + "</table>"
                + "</body>"
                + "</html>";
    }

    public String taskDeadlineHtml(String userName, String taskTitle, String projectName,String day, String taskLink) {
        return ""
                + "<!DOCTYPE html>"
                + "<html lang=\"en\">"
                + "<head>"
                + "<meta charset=\"UTF-8\">"
                + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
                + "<title>Task Deadline Notification</title>"
                + "<style>"
                + "body, html {"
                + "    margin: 0;"
                + "    padding: 0;"
                + "}"
                + ".container {"
                + "    width: 100%;"
                + "    max-width: 600px;"
                + "    margin: 0 auto;"
                + "    padding: 20px;"
                + "    font-family: Arial, sans-serif;"
                + "}"
                + ".header {"
                + "    margin-bottom: 20px;"
                + "    text-align: center;"
                + "}"
                + ".logo {"
                + "    display: flex;"
                + "    align-items: center;"
                + "    justify-content: center;"
                + "    justify-self: flex-start;"
                + "    align-self: flex-start;"
                + "    max-width: 50px;"
                + "    height: auto;"
                + "    margin-right: 20px;"
                + "}"
                + ".header h2 {"
                + "    padding: 10px;"
                + "    border-radius: 5px;"
                + "    color: #fff;"
                + "    background-color: #339AF0;"
                + "}"
                + ".content {"
                + "    text-align: start;"
                + "    padding: 20px;"
                + "    background-color: #cdcdcd;"
                + "    border-radius: 5px;"
                + "    color: #333;"
                + "}"
                + ".button {"
                + "    display: inline-block;"
                + "    background-color: #007bff;"
                + "    color: #fff;"
                + "    text-decoration: none;"
                + "    padding: 10px 20px;"
                + "    border-radius: 5px;"
                + "    margin-top: 20px;"
                + "}"
                + ".footer {"
                + "    margin-top: 20px;"
                + "    text-align: center;"
                + "    color: #666;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<table class=\"container\">"
                + "    <tr>"
                + "        <td class=\"header\" colspan=\"2\">"
                + "            <img src=\"/static/images/logo.png\" alt=\"Project Logo\" class=\"logo\">"
                + "            <h2>Task Deadline Notification</h2>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"content\" colspan=\"2\">"
                + "            <p>Dear " + userName + ",</p>"
                + "            <p>This is to inform you that the following task is due soon:</p>"
                + "            <table>"
                + "                <tr>"
                + "                    <td><strong>Task Title:</strong></td>"
                + "                    <td>" + taskTitle + "</td>"
                + "                </tr>"
                + "                <tr>"
                + "                    <td><strong>Project Title:</strong></td>"
                + "                    <td>" + projectName + "</td>"
                + "                </tr>"
                + "                <tr>"
                + "                    <td><strong>Task Due Date::</strong></td>"
                + "                    <td>" + day + "</td>"
                + "                </tr>"
                + "            </table>"
                + "            <p>Please ensure to complete the task before the deadline.</p>"
                + "            <a href=\"" + taskLink + "\" class=\"button\">Go to Task</a>"
                + "        </td>"
                + "    </tr>"
                + "    <tr>"
                + "        <td class=\"footer\" colspan=\"2\">"
                + "            <p>This is an automated notification. Please do not reply.</p>"
                + "        </td>"
                + "    </tr>"
                + "</table>"
                + "</body>"
                + "</html>";
    }



}
